- name: Instalação Docker
  block:
    - name: Dependências do Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      when: ansible_os_family == "Debian"

    - name: Docker GPG Key
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Instalar Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Instalar Docker (RHEL)
      package:
        name: docker
        state: present
      when: ansible_os_family == "RedHat"
  when: "'docker' not in ansible_facts.packages"

- name: Instalação Docker Compose
  block:
    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
        force: yes

    - name: Criando Link Simbólico
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
        force: yes
  when: "'docker-compose' not in ansible_facts.packages"

- name: Iniciar Serviço Docker
  systemd:
    name: docker
    state: started
    append: yes

- name: Adicionar usuário ao grupo Docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

################## Operações DOCKER COMPOSE - BACKEND ##################
- name: Verificar existência do docker-compose.yaml (backend)
  stat:
    path: "{{ backend_deploy_dir }}/docker-compose.yaml"
  register: compose_file

- name: Deploy com Docker Compose (backend)
  community.docker.docker_compose_v2:
    project_src: "{{ backend_deploy_dir }}"
    build: yes
    pull: yes
    restarted: yes
    state: present
  when: compose_file.stat.exists
  environment:
    DOCKER_CLIENT_TIMEOUT: 120
    DOCKER_HTTP_TIMEOUT: 120

- name: Mostar status caso inexistência do docker-compose.yaml (backend)
  debug:
    msg: "Arquivo docker-compose.yaml não encontrado em {{ backend_deploy_dir }}. Favor, verificar repositório."
  when: not compose_file.stat.exists

################## Operações DOCKER COMPOSE - FRONTEND ##################
- name: Verificar existência do docker-compose.yaml (frontend)
  stat:
    path: "{{ frontend_deploy_dir }}/docker-compose.yaml"
  register: compose_file

- name: Deploy com Docker Compose (frontend)
  community.docker.docker_compose_v2:
    project_src: "{{ frontend_deploy_dir }}"
    build: yes
    pull: yes
    restarted: yes
    state: present
  when: compose_file.stat.exists
  environment:
    DOCKER_CLIENT_TIMEOUT: 120
    DOCKER_HTTP_TIMEOUT: 120

- name: Mostar status caso inexistência do docker-compose.yaml (frontend)
  debug:
    msg: "Arquivo docker-compose.yaml não encontrado em {{ frontend_deploy_dir }}. Favor, verificar repositório."
  when: not compose_file.stat.exists
