version: '3.8'

services:
  asrh-frontend:
    image: elLucas12/asrh-frontend
    container_name: asrh-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_API_URL="http://localhost:3001"
    depends_on:
      - asrh-backend
      - mysql

  asrh-backend:
    image: elLucas12/asrh-backend
    container_name: asrh-backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST="127.0.0.1"
      - DB_PORT=3306
      - DB_USERNAME="test_user"
      - DB_PASSWORD="test_password"
      - DB_NAME="asrh_data"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=asrh_data
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
